background #111111
foreground #f5f5f5
cursor #ffffff
cursor_text_color #202020
selection_background #444444
selection_foreground #ffffff
url_color #c7c7c7

color0 #111111
color1 #ffb4ab
color2 #c7c7c7
color3 #bcbcbc
color4 #ffffff
color5 #d6d6d6
color6 #c7c7c7
color7 #f5f5f5
color8 #494949
color9 #93000a
color10 #444444
color11 #3f3f3f
color12 #444444
color13 #dedede
color14 #d6d6d6
color15 #c7c7c7

active_border_color #ffffff
inactive_border_color #8e8e8e
