include colors.conf
include ../themes/current/kitty.conf

font_family JetBrainsMono Nerd Font
font_size 10
confirm_os_window_close 0

shell_integration enabled

cursor_shape beam
cursor_blink_interval 0.5
