#!/usr/bin/env bash
#
# Screen and lock timeouts.
#
# hypridle has no include mechanism, so the timeouts live in a small state
# directory and this script regenerates ~/.config/hypr/hypridle.conf from them.
# install.sh keeps the generated file across reinstalls.
#
# Usage: idle-settings.sh            open the menu
#        idle-settings.sh --apply    regenerate the config and reload hypridle

set -uo pipefail

config_root="${XDG_CONFIG_HOME:-$HOME/.config}"
menu_theme="$config_root/rofi/menu.rasi"
state_dir="$config_root/dotfiles/idle"
conf="$config_root/hypr/hypridle.conf"
awake_pid="${XDG_RUNTIME_DIR:-/tmp}/dotfiles-keep-awake.pid"

mkdir -p "$state_dir"

# Seconds, or "off". These are the timeouts the repo ships with.
default_lock=300
default_dpms=360
default_suspend=900

get() { # get <name> <default>
    local value
    if [[ -r "$state_dir/$1" ]]; then
        value="$(<"$state_dir/$1")"
        [[ -n "$value" ]] && { printf '%s' "$value"; return; }
    fi
    printf '%s' "$2"
}

pretty() { # pretty <seconds|off>
    case "$1" in
        off) printf 'never' ;;
        *)
            if (($1 % 60 == 0)); then printf '%d min' $(($1 / 60)); else printf '%d s' "$1"; fi ;;
    esac
}

# --- generating the config -------------------------------------------------

listener() { # listener <timeout> <on-timeout> [on-resume]
    [[ "$1" == off ]] && return 0
    printf '\nlistener {\n    timeout = %s\n    on-timeout = %s\n' "$1" "$2"
    [[ -n "${3:-}" ]] && printf '    on-resume = %s\n' "$3"
    printf '}\n'
}

apply() {
    local lock dpms suspend
    lock="$(get lock "$default_lock")"
    dpms="$(get dpms "$default_dpms")"
    suspend="$(get suspend "$default_suspend")"

    {
        printf '# Generated by idle-settings.sh. Edit the timeouts through\n'
        printf '# Setup > Screen and lock, or by hand here — a menu change overwrites this file.\n\n'
        printf 'general {\n'
        printf '    lock_cmd = pgrep -x hyprlock || hyprlock\n'
        printf '    before_sleep_cmd = loginctl lock-session\n'
        printf '    after_sleep_cmd = hyprctl dispatch '\''hl.dsp.dpms({ action = "on" })'\''\n'
        printf '    ignore_dbus_inhibit = false\n'
        printf '}\n'
        listener "$lock" 'loginctl lock-session'
        listener "$dpms" "hyprctl dispatch 'hl.dsp.dpms({ action = \"off\" })'" "hyprctl dispatch 'hl.dsp.dpms({ action = \"on\" })'"
        listener "$suspend" 'systemctl suspend'
    } >"$conf.$$" && mv -f "$conf.$$" "$conf"

    if pgrep -x hypridle >/dev/null 2>&1; then
        pkill -x hypridle
        setsid -f hypridle >/dev/null 2>&1
    fi
}

if [[ "${1:-}" == --apply ]]; then
    apply
    exit 0
fi

# --- keep awake ------------------------------------------------------------

awake_active() {
    [[ -r "$awake_pid" ]] && kill -0 "$(<"$awake_pid")" 2>/dev/null
}

toggle_awake() {
    if awake_active; then
        kill "$(<"$awake_pid")" 2>/dev/null
        rm -f "$awake_pid"
        notify-send -a Dotfiles 'Keep awake off' 'The screen locks and sleeps on schedule again.'
    else
        systemd-inhibit --what=idle:sleep --who='dotfiles-keep-awake' \
            --why='Keep awake' sleep infinity >/dev/null 2>&1 &
        printf '%s\n' "$!" >"$awake_pid"
        disown
        notify-send -a Dotfiles 'Keep awake on' 'The screen will not lock or sleep until this is turned off.'
    fi
}

# --- value picker ----------------------------------------------------------

pick_value() { # pick_value <name> <title> <current> <option seconds...>
    local name="$1" title="$2" current="$3"; shift 3
    local option marker selection

    selection="$({
        for option in off "$@"; do
            marker='  '
            [[ "$option" == "$current" ]] && marker=' ●'
            printf '%s %s\t%s\n' "$marker" "$(pretty "$option")" "$option"
        done
    } | rofi -dmenu -i -no-custom -p "$title" -display-columns 1 -theme "$menu_theme")" || return 0

    option="${selection#*$'\t'}"
    [[ -n "$option" && "$option" != "$selection" ]] || return 0
    printf '%s\n' "$option" >"$state_dir/$name"
    apply
    notify-send -a Dotfiles "$title" "Now $(pretty "$option")."
}

# --- menu ------------------------------------------------------------------

while true; do
    lock="$(get lock "$default_lock")"
    dpms="$(get dpms "$default_dpms")"
    suspend="$(get suspend "$default_suspend")"
    awake_state=off
    awake_active && awake_state=on

    selection="$({
        printf '󰌾  %-18s\tlock-now\n' 'Lock now'
        printf '󰅶  %-18s %s\tawake\n' 'Keep awake' "$awake_state"
        printf '󰔛  %-18s %s\tlock\n' 'Lock after' "$(pretty "$lock")"
        printf '󰡆  %-18s %s\tdpms\n' 'Screen off after' "$(pretty "$dpms")"
        printf '󰤄  %-18s %s\tsuspend\n' 'Suspend after' "$(pretty "$suspend")"
    } | rofi -dmenu -i -no-custom -p 'Screen and lock' -display-columns 1 \
        -theme "$menu_theme" -theme-str 'window { width: 400px; }')" || exit 0

    choice="${selection#*$'\t'}"
    [[ -n "$choice" && "$choice" != "$selection" ]] || exit 0

    case "$choice" in
        lock-now) exec hyprlock ;;
        awake) toggle_awake ;;
        lock) pick_value lock 'Lock after' "$lock" 60 120 300 600 900 1800 ;;
        dpms) pick_value dpms 'Screen off after' "$dpms" 60 120 300 600 900 1800 ;;
        suspend) pick_value suspend 'Suspend after' "$suspend" 900 1800 2700 3600 5400 ;;
        *) exit 0 ;;
    esac
done
