background #000000
foreground #f5f5f5
cursor #ffffff
cursor_text_color #000000
selection_background #303030
selection_foreground #ffffff
color0 #111111
color1 #d75f5f
color2 #87af87
color3 #d7af5f
color4 #87afd7
color5 #af87d7
color6 #87d7d7
color7 #d0d0d0
color8 #666666
color9 #ff8787
color10 #afd7af
color11 #ffd787
color12 #afd7ff
color13 #d7afff
color14 #afffff
color15 #ffffff
