[global]
    separator_color = frame
    icon_theme = "Papirus-Dark, Papirus, Adwaita"
[urgency_low]
    background = "#282828f2"
    foreground = "#928374"
    frame_color = "#504945"
[urgency_normal]
    background = "#282828f2"
    foreground = "#d4be98"
    frame_color = "#7daea3"
[urgency_critical]
    background = "#3c2828f2"
    foreground = "#f2e5bc"
    frame_color = "#ea6962"
